/*
 * generated by Xtext 2.13.0
 */
package aitchteeteepie.xtext.dsl.ide


/**
 * Use this class to register ide components.
 */
class CurlBetterThanHttpieIdeModule extends AbstractCurlBetterThanHttpieIdeModule {
}
