/*
 * generated by Xtext 2.13.0
 */
package aitchteeteepie.xtext.dsl.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class CurlBetterThanHttpieScopeProvider extends AbstractCurlBetterThanHttpieScopeProvider {

}
