/*
 * generated by Xtext 2.13.0
 */
package aitchteeteepie.xtext.dsl.formatting2

import aitchteeteepie.xtext.dsl.services.CurlBetterThanHttpieGrammarAccess
import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2

class CurlBetterThanHttpieFormatter extends AbstractFormatter2 {
	
	@Inject extension CurlBetterThanHttpieGrammarAccess
	
	// TODO: implement for 
}
