/*
 * generated by Xtext 2.13.0
 */
package aitchteeteepie.xtext.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CurlBetterThanHttpieStandaloneSetup extends CurlBetterThanHttpieStandaloneSetupGenerated {

	def static void doSetup() {
		new CurlBetterThanHttpieStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
