/*
 * generated by Xtext 2.13.0
 */
package aitchteeteepie.xtext.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CurlBetterThanHttpieRuntimeModule extends AbstractCurlBetterThanHttpieRuntimeModule {
}
