/**
 * generated by Xtext 2.13.0
 */
package aitchteeteepie.xtext.dsl;

import aitchteeteepie.xtext.dsl.AbstractCurlBetterThanHttpieRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CurlBetterThanHttpieRuntimeModule extends AbstractCurlBetterThanHttpieRuntimeModule {
}
