/**
 * generated by Xtext 2.13.0
 */
package aitchteeteepie.xtext.dsl.ide;

import aitchteeteepie.xtext.dsl.ide.AbstractCurlBetterThanHttpieIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CurlBetterThanHttpieIdeModule extends AbstractCurlBetterThanHttpieIdeModule {
}
